#!/bin/bash
#hwTest:
NUM_OF_ITERATIONS=5

######################################
# simulation iterations:
######################################
./SwitchingSimulation.exe 1000 1 2 0.1 0.9 200 2 10 20 180 >./spaceBasedOutput
for ((i=1;i<NUM_OF_ITERATIONS;i++)); do
    ./SwitchingSimulation.exe 1000 1 2 0.1 0.9 200 2 10 20 180 >>./spaceBasedOutput
done

######################################
# convert text to .csv file:
######################################
tr ' ' ',' <./spaceBasedOutput >./commaBaseOutput.csv

#other tests:
#./SwitchingSimulation.exe 100 2 3 0.11 0.22 0.67 0.21 0.22 0.57 100 200 10 15 20 10 20 30